V1190BT_MAKEFILE:=$(lastword $(MAKEFILE_LIST))
V1190BT_BASE=$(dir $(V1190BT_MAKEFILE))

VPATH+=$(V1190BT_BASE)/..:$(V1190BT_BASE):$(V1190BT_BASE)/../socketbuf

INCLUDE += -I$(V1190BT_BASE)/..
CPPFLAGS += $(INCLUDE) -fmessage-length=0 "-DBUILDDATE=$(shell date "+%F %H:%M:%S")" -pthread
LDFLAGS += -pthread 

UNITS = socket Thread thread socketbuf listen

CLEAN+=$(addsuffix .o, $(UNITS))
all: thread socket listen

DEPGEN=$(CXX) -M $(CPPFLAGS) $< | sed 's,\($*\)\[ :]*,\1 $@ : ,g' > $@

%.cpp.d: %.cpp
	@$(DEPGEN)
DEPS=$(addsuffix .cpp.d, $(UNITS))
CLEAN+=$(DEPS)
ifeq "$(filter clean,$(MAKECMDGOALS))" ""
	-include $(DEPS)
endif

LINKCOMMAND=$(CXX) -o $@ $^ $(LDFLAGS)

CLEAN+=socket

socket: socket.o Thread.o socketbuf.o
	$(LINKCOMMAND)

CLEAN+=thread	
thread: thread.o Thread.o socketbuf.o
	$(LINKCOMMAND)

CLEAN+=listen
listen: listen.o 
	$(LINKCOMMAND)

clean:
	rm -f $(CLEAN)
